version: '3.1'

services:
  postgres:
    image: postgres
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: simplenextappdb
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: privatepassword
    ports:
      - 8000:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  local_pgdata:
  pgadmin-data:
