version: '3.1'

services:
  postgres:
    image: postgres
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: simplenextappdb
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: privatepassword
    ports:
      - 8000:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@pgdb:5432/simplenextappdb?schema=public

volumes:
  local_pgdata:
  pgadmin-data:


networks:
  appnet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
