import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient();

export default function Home({ data }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <table>
        <thead>
          <tr>
            <th>Identifiant</th>
            <th>Prénom</th>
            <th>Nom</th>
            <th>Age</th>
          </tr>
        </thead>
        <tbody>
          {
            data.map(item => {
              return (
                <tr key={item.id}>
                  <td>{item.id}</td>
                  <td>{item.firstname}</td>
                  <td>{item.lastname}</td>
                  <td>{item.age}</td>
                </tr>
              );
            })
          }
        </tbody>


      </table>


    </div>
  )
}


export async function getServerSideProps() {
  const persons = await prisma.person.findMany();
  return {
    props: {
      data: persons
    }
  }
}
